const slackUsers = {
    'Gleb Volodin': { id: 'UHB341HGX', nameAnnotate: 'gleb' },
    'Timur Rozovsky': { id: 'UG42QSM0F', nameAnnotate: 'timur' },
    'Desiree Van Adrichem': { id: 'UAHAR78G7', nameAnnotate: 'desiree' },
    'Enav Even Tzur': { id: 'U6M8ZJ93P', nameAnnotate: 'enav.eventzur' },
    'Adam Davis': { id: 'UFZB1T3D5', nameAnnotate: 'adam.davis' },
    'Koby Soto': { id: 'U4LLF5867', nameAnnotate: 'koby' },
    'Ori Cohen': { id: 'U4MDFQKPY', nameAnnotate: 'ori' },
    'נדב רביד': { id: 'U67FZRCHG', nameAnnotate: 'nadavravid' },
    'Tal Zaguri': { id: 'U67GK6HTL', nameAnnotate: 'tal.zaguri' },
    'Guy Barner': { id: 'U67JZ7LH3', nameAnnotate: 'guyba' },
    'Ari Ben-Yehuda': { id: 'U68BLC8AK', nameAnnotate: 'ari' },
    'בן כהן': { id: 'U6GHZ6MBK', nameAnnotate: 'ben.cohen' },
    'Amiad Soto': { id: 'U6GKTDD6D', nameAnnotate: 'amiad' },
    'סרגיי גרינבלט': { id: 'U6H2HF08K', nameAnnotate: 'sergrin' },
    Guru: { id: 'U6H3S8A81', nameAnnotate: 'guru' },
    'אלעד נוטי ': { id: 'U6H6EG3EG', nameAnnotate: 'elad' },
    'אלעד קרמר': { id: 'U6H8RC1GV', nameAnnotate: 'halfypoo' },
    'Liat Abadi': { id: 'U6HH2HSTV', nameAnnotate: 'Liat' },
    'Luciana Coin': { id: 'UHAQVC467', nameAnnotate: 'luciana' },
    'Jira Cloud': { id: 'U6HH4RT99', nameAnnotate: 'jirabot' },
    'עדינה שלדון': { id: 'U6HJB7ERZ', nameAnnotate: 'adina_sheldon' },
    'Leeron Aran': { id: 'U6HQ7542Z', nameAnnotate: 'leeron' },
    'Anya Chanochi': { id: 'U6J3W1WC8', nameAnnotate: 'anya' },
    'Ben Karniel': { id: 'U6J3ZQXU0', nameAnnotate: 'benkarniel' },
    Sameroom: { id: 'U6J8BM33J', nameAnnotate: 'sameroom' },
    'Reut Peer': { id: 'U6JBMFESU', nameAnnotate: 'reut' },
    'Holly Shamraevsky': { id: 'U6JBZVCLQ', nameAnnotate: 'Holly.shamraevsky' },
    'Oren Cohen': { id: 'U6JC9LGJC', nameAnnotate: 'oren.cohen' },
    'Jackie Waik-Atiya': { id: 'U6JCJ84D6', nameAnnotate: 'jackie' },
    'מנדל פול': { id: 'U6JDF5NHF', nameAnnotate: 'paul' },
    'Sierra Goldie': { id: 'U6JDT7F3K', nameAnnotate: 'sierra' },
    'Jesse Grumet': { id: 'U6JEE98GY', nameAnnotate: 'jesse' },
    'דניאל שרוף': { id: 'UEQL0MJ80', nameAnnotate: 'daniel.sharouf' },
    'marina ortenberg': { id: 'U6JG1S42D', nameAnnotate: 'marinao' },
    'Liora Matatov': { id: 'U6JG7GWJJ', nameAnnotate: 'liora' },
    'Liat Assaf': { id: 'U6JG9CEEA', nameAnnotate: 'liata' },
    'Roman Golbert': { id: 'U8BSFHVK7', nameAnnotate: 'g.roman' },
    'Sheli Grumet': { id: 'U6JLXA1T5', nameAnnotate: 'sheli' },
    'Shiri reich': { id: 'U6JM38H6X', nameAnnotate: 'shiri' },
    Nili: { id: 'U6JMABPEX', nameAnnotate: 'nili' },
    'Tal Sieger': { id: 'U6JN5LHFZ', nameAnnotate: 'tal.sieger' },
    'Joel Musongela': { id: 'U6JQ8RQV8', nameAnnotate: 'joel' },
    'Danielle Reisman Moses': { id: 'U6JQPNQ20', nameAnnotate: 'danielle' },
    'מור קורץ': { id: 'U6JRVS1UG', nameAnnotate: 'mor' },
    'Yael Lopez Jakten': { id: 'U6JS091U3', nameAnnotate: 'yael' },
    'Sharon Gilmour': { id: 'U6JSV2C4B', nameAnnotate: 'sharon' },
    'Rotem Ben-Meir': { id: 'U6JSY8ZN1', nameAnnotate: 'Rotem Ben-Meir' },
    'Hamutal Greenberg': { id: 'U6JT6BT9R', nameAnnotate: 'hamutal' },
    'הגר סנד': { id: 'U6JU9T97T', nameAnnotate: 'hagar' },
    'Andrea Boker': { id: 'U6JV722CA', nameAnnotate: 'andrea' },
    'Jeff Eisenberg': { id: 'U6K0WPC3E', nameAnnotate: 'jeff' },
    'Elisha Leibovich': { id: 'U6K1909U2', nameAnnotate: 'elisha' },
    'Haley Firkser': { id: 'U6K19RJU9', nameAnnotate: 'haleyfirkser' },
    'Aviva Strauss': { id: 'U6K284JGL', nameAnnotate: 'avivastrauss' },
    'תומר רוזנבלום': { id: 'U6K37PT8V', nameAnnotate: 'tomer' },
    'Alix Hirsh': { id: 'U6K38UB0D', nameAnnotate: 'ali_hirsh' },
    'Bar Kinreich': { id: 'U6K4G6CHY', nameAnnotate: 'bar.kinreich' },
    'Nicole Tobin': { id: 'U6K63JLNQ', nameAnnotate: 'nicole' },
    'Ilan Klein': { id: 'U6K8YH7M2', nameAnnotate: 'ilanklein' },
    'Shira Terespolsky': { id: 'U6K91KCLS', nameAnnotate: 'shira.terespolsky' },
    'Autumn Chapman': { id: 'U6KC6PD3L', nameAnnotate: 'autumn' },
    'Sergei Tcheberiachkin': { id: 'U6KCK727M', nameAnnotate: 'sergei.tcheb' },
    'Rivky Robbins': { id: 'U6KDVPU83', nameAnnotate: 'rivkyrobbins' },
    'Moria Avdayev': { id: 'U6KEBDE1J', nameAnnotate: 'Moria' },
    gemma: { id: 'U6KEC393M', nameAnnotate: 'gemma' },
    'Jonathan Decktor Schoenbrunn': { id: 'U6KHRSAP6', nameAnnotate: 'decktor' },
    'Nevo Peleg': { id: 'U6KJ6FZ8S', nameAnnotate: 'nevopeleg' },
    'Arielle Ben-Hashal': { id: 'U6KNVD5ED', nameAnnotate: 'arielle' },
    'Elisa Szklanny': { id: 'U6KP8MS56', nameAnnotate: 'elisaszklanny' },
    'Eleanor Paz': { id: 'U6KQLA23E', nameAnnotate: 'eleanorpaz' },
    'Tiferet Zussman': { id: 'U6KR3ALSJ', nameAnnotate: 'tiferet' },
    'Maxi Rapaport': { id: 'U8APVNT50', nameAnnotate: 'maxi.rapaport' },
    'Joseph Binestock': { id: 'U6KS32M71', nameAnnotate: 'joseph' },
    'Miriam Alessio': { id: 'U8A10TKJM', nameAnnotate: 'miriam.alessio' },
    'סלבה יעקובסון ': { id: 'U6KUC9T62', nameAnnotate: 'slavik' },
    'Ronnie Markevich': { id: 'U6L39MPA6', nameAnnotate: 'ronniemarkevich' },
    'Julie Cranston': { id: 'U8BK0MS3U', nameAnnotate: 'julie.cranston' },
    'Ela Zomer': { id: 'U6L5DQG8J', nameAnnotate: 'elazomer' },
    'Aliza Katz': { id: 'U6L799MSN', nameAnnotate: 'aliza' },
    'Jason Silverman': { id: 'U6L7D9B7E', nameAnnotate: 'jasonsilverman1' },
    'Nickoma Ceaser': { id: 'U6L8MUUK1', nameAnnotate: 'nickoma' },
    'Dima Paley': { id: 'U6LAGE15E', nameAnnotate: 'captain_fantastic' },
    'Noam Yaron': { id: 'U6LFHM338', nameAnnotate: 'noam' },
    'Lior Cohen': { id: 'U6LG6CG06', nameAnnotate: 'liorcohen' },
    'yair Moses': { id: 'U6LGCSE14', nameAnnotate: 'yairmoses' },
    'Gedaliah Bernstein': { id: 'U6LKR6TJP', nameAnnotate: 'gedaliah' },
    'Adam Har Shemesh': { id: 'U6LR78M96', nameAnnotate: 'adamtokillfor' },
    'Rachel BenHanoch': { id: 'U6LV6BX99', nameAnnotate: 'rachel' },
    'Yair Simo': { id: 'U6M3L54Q6', nameAnnotate: 'lucas-simo' },
    'mohr wenger': { id: 'U6M8N29B2', nameAnnotate: 'mohr' },
    'Enav Even Tzur': { id: 'U6M8ZJ93P', nameAnnotate: 'enav' },
    'Ruthie Golomb': { id: 'U6MC3UQFK', nameAnnotate: 'ruthiegolomb' },
    'Irina Bespalova': { id: 'U6MDUEMU0', nameAnnotate: 'irina' },
    'Alina Jo': { id: 'U8D8D7SHM', nameAnnotate: 'Alina Jo' },
    'Dan Lesser': { id: 'U6MLSHR63', nameAnnotate: 'benjamin' },
    'tyrone plint': { id: 'U6N04JQ04', nameAnnotate: 'tyroneplint' },
    'Julia Rios': { id: 'U8B1A96PN', nameAnnotate: 'julia.rios' },
    'andrea feldman': { id: 'U6N2A5STF', nameAnnotate: 'deiafeldman' },
    'Iris Santo': { id: 'U6P123FAB', nameAnnotate: 'irissanto' },
    'Yonatan Hengly': { id: 'U6R0JCNEP', nameAnnotate: 'yonatanh' },
    'אבישי מאור': { id: 'U6S5AA60N', nameAnnotate: 'avishay' },
    'Itay Tuson': { id: 'U6V117XR9', nameAnnotate: 'itayt' },
    'shai klein': { id: 'U6V38TR4J', nameAnnotate: 'shai' },
    'Mimi Schachat': { id: 'U6V38TURG', nameAnnotate: 'mimi' },
    'Alex Reidler': { id: 'U6V503RJ8', nameAnnotate: 'alexreidler' },
    'Camila Rosero': { id: 'U8BAN1UR3', nameAnnotate: '' },
    'Anna Miroshnichenko': { id: 'U6V786S0M', nameAnnotate: 'annami' },
    'Vera Blitshtein': { id: 'U6XGKQSBS', nameAnnotate: 'vera' },
    'Rachel Weiss': { id: 'UARFVL5C5', nameAnnotate: 'Rachel Weiss' },
    'Julia Rainesh': { id: 'U6XK0SL5A', nameAnnotate: 'julia' },
    'Rimon Arieli': { id: 'U70ES608G', nameAnnotate: '' },
    'Yoram Kornatzky': { id: 'U7185HA65', nameAnnotate: 'kornatzky' },
    'Gil Eiges': { id: 'U7275P3AS', nameAnnotate: 'gil' },
    'Orr Grosman': { id: 'U747S2ZUK', nameAnnotate: '' },
    'Angela Shaul': { id: 'U74C5U90U', nameAnnotate: 'Angela' },
    'Lena Pavlushko': { id: 'U7ABU32KG', nameAnnotate: 'lena' },
    'Shiri Labi': { id: 'U7ATNPESU', nameAnnotate: 'shirilabi' },
    'Hanna Sanden': { id: 'U7B1JMPR7', nameAnnotate: 'Hanna' },
    'Noam Levin': { id: 'U7B1JN649', nameAnnotate: '' },
    'Nurit Sinay': { id: 'U7BFFG7HR', nameAnnotate: 'nurit' },
    'Avigail Siman Tov': { id: 'U8AGXEJ72', nameAnnotate: 'Abigail' },
    'מוטי דאדיסון ': { id: 'U7BHUK9M2', nameAnnotate: 'motti' },
    'Max Bernstein': { id: 'U7CD54A30', nameAnnotate: '' },
    'Daniel Cohen': { id: 'U7CDENLQ6', nameAnnotate: 'Daniel' },
    'Google Drive': { id: 'U7F5HGCAY', nameAnnotate: '' },
    'Nadav Marmur': { id: 'U8BL97NS1', nameAnnotate: 'nathaniel' },
    vaidas: { id: 'U7JS0CTSQ', nameAnnotate: 'vaidas' },
    robin: { id: 'U7NHU1JQ0', nameAnnotate: '' },
    'Jessica Gillingham': { id: 'U7PJCL1H8', nameAnnotate: 'Jessica' },
    'Erez Zohar': { id: 'U7PPMU7FX', nameAnnotate: 'Erez Zohar' },
    'Joanna Palmer': { id: 'U7QJH4GSF', nameAnnotate: '' },
    'פוגול ג׳ורדן מיכאל': { id: 'U7SJQKN49', nameAnnotate: 'jordan' },
    'Yael Snir': { id: 'U7TUSK1EZ', nameAnnotate: 'Yael S' },
    'Sapir Keret': { id: 'U7U1SA8ES', nameAnnotate: 'sapir' },
    'Hadar Navon': { id: 'U7U23EPPG', nameAnnotate: '' },
    'Tanya Yakovlev': { id: 'U7USE3W3H', nameAnnotate: 'Tanya' },
    Liat: { id: 'U7W9U5Y7R', nameAnnotate: 'Liata' },
    'Daniel Rev': { id: 'U7YUJ247L', nameAnnotate: 'Daniel' },
    'Dana Cooper': { id: 'U7Z1XQ0VB', nameAnnotate: 'dana' },
    Sasha: { id: 'U805QUBBQ', nameAnnotate: '' },
    'Natalia Kushnir': { id: 'U83GT24JW', nameAnnotate: '' },
    'Dan Weinberg': { id: 'U86JC56DD', nameAnnotate: 'Dan' },
    'אייל רונאל': { id: 'U88RYJ799', nameAnnotate: 'Eyal Ronel' },
    'Lital Lotan': { id: 'U89NYCVD4', nameAnnotate: 'lital' },
    'Jonathan Decktor': { id: 'U8B6RH59T', nameAnnotate: 'jonathan.decktor' },
    hs: { id: 'U8B7NA39T', nameAnnotate: '56556565' },
    'Shai Klein': { id: 'U8B8TFRQD', nameAnnotate: 'shai' },
    'Adam Harshemesh': { id: 'U8BTB00JD', nameAnnotate: 'Adam Har Shemesh' },
    'Anna Mi': { id: 'U8C247TU0', nameAnnotate: 'anna.miroshnichenko' },
    'Gadi Bernstein': { id: 'U8D80RW86', nameAnnotate: '' },
    'Or Geva': { id: 'U8DDK8R4G', nameAnnotate: 'or' },
    Sergei: { id: 'U8FJF4CTG', nameAnnotate: 'sergei.t' },
    'Jonathan Baker': { id: 'U8FTJ3BMJ', nameAnnotate: 'Jonathan Baker' },
    'Oleg Miller': { id: 'U8G8YRDS9', nameAnnotate: 'Miller' },
    'Hadar Raveh': { id: 'U8JT0V924', nameAnnotate: 'hadar.raveh' },
    'Stephen Ganz': { id: 'U8L54A6CQ', nameAnnotate: 'Steve' },
    'Elane Conway': { id: 'U9GTJV1H8', nameAnnotate: '' },
    'Avi Ostrow': { id: 'U8LNPR9NF', nameAnnotate: 'Avi Ostrow' },
    'David Allen': { id: 'U8MSDSLBZ', nameAnnotate: 'david.allen' },
    'אנטולי אוטקין': { id: 'U8Q31V91S', nameAnnotate: 'anatoly' },
    'Kevin J. Hanna': { id: 'U8SFEUXMH', nameAnnotate: 'kevin' },
    'Avital Greenfest': { id: 'U8SQRNFB3', nameAnnotate: 'Avital Greenfest' },
    'Tanvi Kalra': { id: 'U8SSNFVPV', nameAnnotate: 'Tanvi' },
    'Shir Guy': { id: 'U8VLPM1K3', nameAnnotate: '' },
    'Dmytro Grama': { id: 'U927NK3C1', nameAnnotate: 'dmytro' },
    'Fernanda Faure': { id: 'U8WCS6AQ4', nameAnnotate: '' },
    'ולאד גולדמן': { id: 'U8XQV03L2', nameAnnotate: 'vlad' },
    'Aylin Tzemach': { id: 'U8Y837BT9', nameAnnotate: 'Aylin Tzemach' },
    'Matthew Moscovitch': { id: 'U8YRG88S3', nameAnnotate: 'matthew' },
    'Orya Uziel': { id: 'U8ZDEQ82U', nameAnnotate: '' },
    'Orit Tepper': { id: 'U9262LAA0', nameAnnotate: 'orit' },
    'Nazar Trynko': { id: 'U926H255G', nameAnnotate: 'Nazar Trynko' },
    'mor naaman': { id: 'U93AV73F1', nameAnnotate: '' },
    'Natasha Amoyal': { id: 'U93PYFJLA', nameAnnotate: 'Tasha CSM' },
    'מיכל אסתר פריאר': { id: 'U945ZANMB', nameAnnotate: 'michal' },
    'Lou Riboh': { id: 'U952W2Y2K', nameAnnotate: 'Lou Riboh' },
    'Liana Asuleen': { id: 'U96RG6E00', nameAnnotate: '' },
    'Lidor Atari': { id: 'U97EKD6BW', nameAnnotate: '' },
    'Gabriella Katz': { id: 'U97FG3A6P', nameAnnotate: '' },
    'Michael Schiff': { id: 'U9BSF4XC5', nameAnnotate: '' },
    'Eric Gamil': { id: 'U97LK984V', nameAnnotate: '' },
    Artem: { id: 'U97JJPQRF', nameAnnotate: 'artem' },
    'Michael Feldman': { id: 'U992KE2A2', nameAnnotate: '' },
    'Amani Shourbaji': { id: 'U97KN1BSL', nameAnnotate: 'iAmani' },
    'Shlomo Amor': { id: 'U98Q3EYK0', nameAnnotate: '' },
    'Koby Bentata Goldenberg': { id: 'U98QY0L9J', nameAnnotate: '' },
    'Na\'ama Shoshani': { id: 'U998200F2', nameAnnotate: 'naama.shoshani' },
    ajk: { id: 'U9A7QQVRN', nameAnnotate: '' },
    'Mauro Manero': { id: 'U9AAEJAG1', nameAnnotate: 'mauro' },
    'Galia Kelman': { id: 'U9C1NLS0Z', nameAnnotate: 'Galia' },
    'Lauren Nicole Pace': { id: 'U9AAZ6Q2V', nameAnnotate: 'LaurenPace' },
    'Lauren Pace': { id: 'U9BFZ6EHH', nameAnnotate: 'Lauren' },
    'Eden Yair-Melo': { id: 'U9BPW4X46', nameAnnotate: 'Eden Yair Melo' },
    'Anna Wojciechowska': { id: 'U9BUVCZT9', nameAnnotate: 'Anna Wojciechowska' },
    'Yoni Mashasha': { id: 'U9D6T9NR4', nameAnnotate: 'yoni' },
    'Neta Kafry': { id: 'U9EKZKM5Z', nameAnnotate: 'Netak' },
    'anna kalashnik': { id: 'U9ELARKA7', nameAnnotate: '' },
    'Kialash Persad': { id: 'U9EN8AW0L', nameAnnotate: '' },
    'Gabriel Kessler': { id: 'U9FD91XT6', nameAnnotate: 'Gabriel' },
    'Shelbi Lifshitz': { id: 'U9FFF21QX', nameAnnotate: 'Shelbi' },
    'Mike Bergman': { id: 'U9GEM41EK', nameAnnotate: 'mike' },
    'Yoav Lebens': { id: 'U9HU1VCP2', nameAnnotate: 'Yoav' },
    'Abi Rod': { id: 'U9J7EM9J6', nameAnnotate: 'abi' },
    'Mayer Roth': { id: 'U9JDF0VPX', nameAnnotate: 'Mayeroth' },
    'Jordan Lewis': { id: 'U9K2W1U8N', nameAnnotate: 'jordan.lewis' },
    'Alex Ravikovich': { id: 'U9MSPA4DQ', nameAnnotate: 'alex' },
    'Gabriel Cinato': { id: 'U9P8K2B9D', nameAnnotate: 'gabriel.cinato' },
    'Dudu Sayag': { id: 'U9PP04ZME', nameAnnotate: 'dudu' },
    'Gal Chen': { id: 'U9Q9HH45S', nameAnnotate: '' },
    'Ariel Sinvany': { id: 'U9R4QNXKJ', nameAnnotate: 'ariel' },
    'yonah zeff': { id: 'U9S3U5EU8', nameAnnotate: 'Yonah' },
    'Loura Marquez': { id: 'U9S4G3M0T', nameAnnotate: 'Loura' },
    'Gabriel Rehfeld': { id: 'U9VC3RDS4', nameAnnotate: '' },
    'Bruna Kirszenworcel': { id: 'U9T4NNZU7', nameAnnotate: 'Bruna Kirszenworcel' },
    'Zahava Wesfield': { id: 'U9TEBN89Y', nameAnnotate: 'Zahava' },
    'Nathan Herz': { id: 'U9UD49KPX', nameAnnotate: 'Nathan' },
    'Matan Rokach': { id: 'U9WP6LPDX', nameAnnotate: '' },
    'Iris Sherman': { id: 'U9Y7Q8LMQ', nameAnnotate: 'iris' },
    'Manor Zikri': { id: 'U9Z7YPHJP', nameAnnotate: 'Manor' },
    'Ainav Weisberg': { id: 'UA0CGCGSK', nameAnnotate: 'ainav.weisberg' },
    'Murron Carroll': { id: 'UA0DA1QES', nameAnnotate: '' },
    'Nazar Lytvynenko': { id: 'UA13J81P0', nameAnnotate: 'Nazar L' },
    'Dmitry Yourkevich': { id: 'UA1UYBUL9', nameAnnotate: 'Dima' },
    'לי עופרי': { id: 'UA2KDPSC8', nameAnnotate: 'lee' },
    'info-bot': { id: 'UA2KSRNUU', nameAnnotate: '' },
    'Michal Crystal': { id: 'UA3EJSKHQ', nameAnnotate: 'Michal C' },
    'Omer Brand': { id: 'UA4EWE4TZ', nameAnnotate: 'omer.brand' },
    'Ksenia Glushkova': { id: 'UA5V5SEP2', nameAnnotate: 'Ksenia' },
    'Ronnie Mordekhayev': { id: 'UA6C25BRR', nameAnnotate: 'Ronnie' },
    'Neshama Lopez': { id: 'UA6MKK468', nameAnnotate: '' },
    'נג`יב אלשמלה': { id: 'UA733RX5Y', nameAnnotate: 'najeeb' },
    'Jacquie Vincent': { id: 'UA77WMGBD', nameAnnotate: 'Jacquie' },
    'Erik Claster': { id: 'UA7RUTD1A', nameAnnotate: 'Viking Erik' },
    'Shaked Sayag': { id: 'UA8AK01JB', nameAnnotate: 'Shaked' },
    'Iris Stodomingo': { id: 'UA8AYS7U0', nameAnnotate: 'Iris Santo' },
    'מת`יו ג`ייקוב אולרש': { id: 'UAC8FPD8R', nameAnnotate: 'matthew.olarsch' },
    'Tamar Daniel': { id: 'UACFVDUMP', nameAnnotate: 'tamar' },
    'ימית עצמון': { id: 'UACP04TJ7', nameAnnotate: '' },
    'Amir Friedman': { id: 'UAFM81Y3S', nameAnnotate: '' },
    'Noor Asendar': { id: 'UAG4MCVMW', nameAnnotate: '' },
    'Tal Brayer': { id: 'UAGCCT3R8', nameAnnotate: 'Tal Brayer' },
    'Robyn Hall': { id: 'UAGD40WMB', nameAnnotate: 'Robyn' },
    'Noa Matz': { id: 'UAGDR7M3P', nameAnnotate: '' },
    'Desiree van Adrichem': { id: 'UAHAR78G7', nameAnnotate: 'desiree' },
    'Andriy Rybak': { id: 'UAHVBM7UN', nameAnnotate: 'andriy.b' },
    'Cory Adelman': { id: 'UAKHV9EG5', nameAnnotate: 'Cory Adelman' },
    'Amit Zelinger': { id: 'UAMC5NRRA', nameAnnotate: 'amit.zelinger' },
    'Ellie Reading': { id: 'UAR3VUH7W', nameAnnotate: 'ellie' },
    'Yaniv Kalmek': { id: 'UASFX9W3S', nameAnnotate: '' },
    'John Kariuki': { id: 'UAUBJC0DA', nameAnnotate: 'kariuki' },
    'Mel Michael': { id: 'UAUN96HPF', nameAnnotate: 'charmingmel' },
    'Mark Giliadov': { id: 'UAV8B6G1J', nameAnnotate: 'Mark Giliadov' },
    'Roy Rutto': { id: 'UAVF2M0ES', nameAnnotate: 'roy' },
    'סולומון בריהון': { id: 'UAXS653EH', nameAnnotate: 'solomon' },
    'Assaf Rotchild': { id: 'UAYB884RF', nameAnnotate: 'assaf' },
    'Matthew Barnes': { id: 'UB12TQ44A', nameAnnotate: 'matthew.barnes' },
    'Meira Friedland': { id: 'UB12UR5TL', nameAnnotate: 'Meira Friedland' },
    'Michal Israel': { id: 'UB2LUF37W', nameAnnotate: '' },
    'Lianna H Lieberman': { id: 'UB456BVU0', nameAnnotate: 'Lili' },
    'Aviv Gete': { id: 'UB45XPT7A', nameAnnotate: 'AvivG' },
    'Gal Gordon': { id: 'UB5JYP4LS', nameAnnotate: 'gal.gordon' },
    'Ofir Malka': { id: 'UB6HANG1M', nameAnnotate: 'ofir' },
    'Jonaias  Maceda': { id: 'UB6MS0GSV', nameAnnotate: 'Joe Maceda' },
    'Jonalyn Joy  Verlising': { id: 'UB6N6B22D', nameAnnotate: 'Joya' },
    'חיים יהודה אריה זילבר': { id: 'UB6N8TE9H', nameAnnotate: 'chaim' },
    'Marie Endaya': { id: 'UB721MUDA', nameAnnotate: 'Marie' },
    'Demsy  Antonio': { id: 'UB7277UUC', nameAnnotate: 'demsy.antonio' },
    'Anna Reotutar': { id: 'UB75N53PD', nameAnnotate: 'Anna' },
    'Yani Lazada': { id: 'UB7CY3BE1', nameAnnotate: 'Yani' },
    'Mario Paolo  Kimseng': { id: 'UB7D2F72R', nameAnnotate: 'Marlo Kimseng' },
    'Cresca Camille  Alcantara': { id: 'UB7PUFFQF', nameAnnotate: 'Nikki' },
    'Ken Hirai': { id: 'UB8AABF55', nameAnnotate: 'Ken' },
    'James Muturi': { id: 'UBBH6NEQY', nameAnnotate: 'james' },
    'Uri Ilan': { id: 'UBBQ3JKEU', nameAnnotate: '' },
    'James Henderson': { id: 'UBDRE3SLC', nameAnnotate: '' },
    'Haish Harel': { id: 'UBF63KPAL', nameAnnotate: 'Haish' },
    'Amanda Kanners': { id: 'UBLH86KG9', nameAnnotate: 'amanda' },
    'Bohdan Rutylo': { id: 'UBNKULUJZ', nameAnnotate: '' },
    'Archie Victa': { id: 'UBNQR8YGZ', nameAnnotate: 'Archie' },
    'Ian Ongcoy': { id: 'UBNRN2E4R', nameAnnotate: 'ian.ongcoy' },
    'Juan Dominic Bautista': { id: 'UBP8DLXGB', nameAnnotate: 'Nick' },
    'Cyril Esguerra': { id: 'UBPAJTF25', nameAnnotate: 'Cyril' },
    'Sugar Anne Rocco': { id: 'UERQ5BCTY', nameAnnotate: 'sugar.rocco' },
    'Maja Facton': { id: 'UBPSW9DS6', nameAnnotate: 'Maja' },
    'Jorge Jarical': { id: 'UBQJN60BY', nameAnnotate: 'Jorge' },
    'Kris Dayao': { id: 'UBR0M4T50', nameAnnotate: 'Kris' },
    'John Earl Batungbacal': { id: 'UBR51591C', nameAnnotate: 'Earl' },
    'Vered Raviv Schwarz': { id: 'UBRQLTSBH', nameAnnotate: '' },
    'Aaron Cedric Verdadero': { id: 'UBRRC48CF', nameAnnotate: 'Cedric Verdadero' },
    'Itay Levy': { id: 'UBRTU68S1', nameAnnotate: 'itay' },
    'Jeremy Kithome': { id: 'UBS2JBSG1', nameAnnotate: 'jeremy_ooo' },
    'Omri Cohen': { id: 'UBS4NKB8W', nameAnnotate: 'Omri' },
    'Debbie Agoot': { id: 'UBTUKFTE1', nameAnnotate: 'Debbie Agoot' },
    'דמיטרי גרויסמן': { id: 'UBU435L72', nameAnnotate: 'dima.groisman' },
    'Adam Daniel Shemesh': { id: 'UBUH30TU4', nameAnnotate: 'Adam Shemesh' },
    'מיטל וייס': { id: 'UBVSY9N8Y', nameAnnotate: 'Meital Weiss' },
    'Gary Yusupov': { id: 'UBXGS0CLD', nameAnnotate: '' },
    'Mollie Zabar': { id: 'UBXK1P7LM', nameAnnotate: 'mollie.zabar' },
    'Jonathan Yehie': { id: 'UBYG05H99', nameAnnotate: 'Jony-Y' },
    'Avi Osipov': { id: 'UC1CZ3A9Z', nameAnnotate: 'avi.osipov' },
    'Ruth Ogendi': { id: 'UC2DG03H8', nameAnnotate: 'bopchy' },
    'Charles Muthini': { id: 'UC2H4RBPH', nameAnnotate: 'charles' },
    'Dmitry Vislov': { id: 'UC2VAPSVA', nameAnnotate: 'dimi' },
    'Stephie Marcelo': { id: 'UC3H2C1SM', nameAnnotate: 'stephanie.marcelo' },
    Joy: { id: 'UC3TJJ9BJ', nameAnnotate: 'Joy' },
    donut: { id: 'UC41HN9QQ', nameAnnotate: '' },
    'Jennifer Jamili': { id: 'UC42YPAD7', nameAnnotate: 'Jenn' },
    'Sha Arce': { id: 'UC4C2QBE0', nameAnnotate: 'shara.arce' },
    'Charlston Joaquin': { id: 'UC4CB8UD9', nameAnnotate: 'joaquin.charleston' },
    'Jackie Rosales': { id: 'UC4FAUKT5', nameAnnotate: 'jackie.rosales' },
    'Danlee Clamor': { id: 'UC4PA5VGD', nameAnnotate: 'danlee.clamor' },
    'Jed Volante': { id: 'UC4PA8FV3', nameAnnotate: 'john.volante' },
    'Jan Noel Carlo Teope': { id: 'UC4PADAN9', nameAnnotate: 'carlo.teope' },
    'Lorenz Magboo': { id: 'UC4PBM02H', nameAnnotate: 'lorenz.magboo' },
    'Penney A. Besonia': { id: 'UC4PBQ5RT', nameAnnotate: 'Penney' },
    'Roman Sarabun': { id: 'UC6PHRKAL', nameAnnotate: 'roman.sarabun' },
    'Lena Gura': { id: 'UC6RWGXFY', nameAnnotate: 'Lena' },
    'Lea Benmayor': { id: 'UC6UDSY57', nameAnnotate: 'lea.benmayor' },
    'Dana Madari': { id: 'UCAENEWCQ', nameAnnotate: '' },
    'Nataliia Voloshyn': { id: 'UCCFXRLCX', nameAnnotate: '' },
    'Vadym Padalko': { id: 'UCD1B18UW', nameAnnotate: 'vpadalko' },
    'Jonathan Cohen': { id: 'UCD3K4KPA', nameAnnotate: 'jonathan.cohen' },
    'Joy Warugu': { id: 'UCFJQSWF3', nameAnnotate: 'joykare' },
    'Gil Wasserman': { id: 'UCFLSQ6AC', nameAnnotate: '' },
    'Eric Limos': { id: 'UCGTA8D6G', nameAnnotate: 'eric.limos' },
    'Steph Medina': { id: 'UCGTAC14L', nameAnnotate: 'Steph' },
    'Trix Pangan': { id: 'UCGTANDD2', nameAnnotate: 'trix.pngan' },
    'Michael Angelo O. Aranzanso': { id: 'UCH8WG2HK', nameAnnotate: 'Mico' },
    'Franzy Milanio': { id: 'UCJ5KKCQ7', nameAnnotate: 'franzy.milanio' },
    'Mark Davis De Guzman': { id: 'UCJEHDYR4', nameAnnotate: 'Mark' },
    'Coby Soffer': { id: 'UCK1V6SQ0', nameAnnotate: 'Coby' },
    'Maksym Shpak': { id: 'UCKQPTG92', nameAnnotate: 'maksym.shpak' },
    'Slava Borodovsky': { id: 'UD0JALN80', nameAnnotate: 'Slava' },
    'Romi Tendler': { id: 'UCSC8PA82', nameAnnotate: 'romi' },
    'Sophya Schnitman': { id: 'UCSFBAM7V', nameAnnotate: 'sophya.schnitman' },
    'תומר ברקת': { id: 'UCSSW795M', nameAnnotate: 'tomer.bareket' },
    'Alana Mehaber': { id: 'UCU9G30SG', nameAnnotate: 'Alana M.' },
    'Doron Pryluk': { id: 'UD139FUA0', nameAnnotate: 'doronpryluk' },
    'Rita Yoffe Boaz': { id: 'UD51ABEFM', nameAnnotate: 'Rita' },
    'שיר רז': { id: 'UD8JJBTFG', nameAnnotate: 'shir' },
    'Gideon Gitau': { id: 'UDB9MF354', nameAnnotate: 'gg' },
    'Nesya Gilad': { id: 'UDELX9664', nameAnnotate: 'nesya' },
    'Ron Artenstein': { id: 'UDFHCRFRC', nameAnnotate: 'ron' },
    'Tonette Laquian': { id: 'UDFV6B1BM', nameAnnotate: 'mary.laquian' },
    'Astrid Niana Amigo': { id: 'UDG2G3B18', nameAnnotate: 'astrid.amigo' },
    'Jb Mercado': { id: 'UDG2G6WHG', nameAnnotate: 'john.mercado' },
    'Rochelle Caparas': { id: 'UDH42SUS3', nameAnnotate: 'rochelle.caparas' },
    'Ardie Agoylo': { id: 'UDHDCMUKY', nameAnnotate: 'Ardie' },
    'Janice Avelino': { id: 'UDHDCSQUW', nameAnnotate: 'janice.avelino' },
    'Moriya Blumenfeld': { id: 'UDPUNU5EG', nameAnnotate: 'moriya' },
    'Joshua Silverberg': { id: 'UDQQGFSDT', nameAnnotate: 'Josh' },
    'Alon Eini': { id: 'UE06LUPK3', nameAnnotate: 'alon.eini' },
    Inbal: { id: 'UE1ATJCLU', nameAnnotate: 'Semach' },
    'Oleksiy Shreder': { id: 'UE1NWJWP3', nameAnnotate: 'oleksiy' },
    'Dmytro Ukolov': { id: 'UE5MQ4S77', nameAnnotate: 'dmytro.ukolov' },
    'Lauren Gumport': { id: 'UE7UACV9S', nameAnnotate: 'lauren' },
    'Nir Hemo': { id: 'UE9CEUW5D', nameAnnotate: 'nir' },
    'Yuliya Rozhavsky': { id: 'UEBCFR23U', nameAnnotate: 'yuliya' },
    'Alex Cohen': { id: 'UEBHSTL11', nameAnnotate: 'alex.cohen' },
    'Carly Meskin': { id: 'UEH99CB7C', nameAnnotate: 'carly' },
    'Gal Jacubovitch': { id: 'UENDZNAFJ', nameAnnotate: 'gal.j' },
    'Abby Matlin': { id: 'UEMUU6FD5', nameAnnotate: 'abby' },
    'Itay Oren': { id: 'UEP6D9LBC', nameAnnotate: 'itay.oren' },
    'joya verlising': { id: 'UEQ8YF97F', nameAnnotate: 'joya.verlising' },
    'nikki.alcantara': { id: 'UEQEU68KG', nameAnnotate: 'nikki.alcantara' },
    'דניאל שרוף': { id: 'UEQL0MJ80', nameAnnotate: 'daniel.sharouf' },
    'ken.hirai': { id: 'UEQN7R5GV', nameAnnotate: 'ken.hirai' },
    hakam: { id: 'UEUFTRHS5', nameAnnotate: 'hakam' },
    'debbie.agoot': { id: 'UEUN8B9B6', nameAnnotate: 'debbie.agoot' },
    'marie.endaya': { id: 'UEVNCG1T9', nameAnnotate: 'marie.endaya' },
    'Meir Gold': { id: 'UF0HE9WMS', nameAnnotate: 'meir.gold' },
    'elad.silvas': { id: 'UF0KF66V9', nameAnnotate: 'elad.silvas' },
    'בן דוד': { id: 'UF0NN0TT4', nameAnnotate: 'ben.david' },
    'david.finkelstein': { id: 'UF3ME006L', nameAnnotate: 'david.finkelstein' },
    'Roman Marshevskyy': { id: 'UF6F1BCBD', nameAnnotate: 'roman.marshevskyy' },
    'Stephanie Elek': { id: 'UF6LU20H5', nameAnnotate: 'stephanie.elek' },
    'andrei.smirnov': { id: 'UF6SADR89', nameAnnotate: 'andrei.smirnov' },
    'raphael.ferraz': { id: 'UF78FH2JC', nameAnnotate: 'raphael.ferraz' },
    'Jérôme Jutzi': { id: 'UF7J487MX', nameAnnotate: 'jerome.jutzi' },
    deborah: { id: 'UF7UW6Q1G', nameAnnotate: 'deborah' },
    'jene.rhodes': { id: 'UF8MM677U', nameAnnotate: 'jene.rhodes' },
    adi: { id: 'UF8U7RRFG', nameAnnotate: 'adi' },
    'jason.pavlow': { id: 'UF94QP84R', nameAnnotate: 'jason.pavlow' },
    'diego.halegua': { id: 'UFA3TLCU8', nameAnnotate: 'diego.halegua' },
    'oren.neiberg': { id: 'UFCCMBJF5', nameAnnotate: 'oren.neiberg' },
    'gal.avraham': { id: 'UFCP3Q0SY', nameAnnotate: 'gal.avraham' },
    'yoav.martin': { id: 'UFD4JAMV3', nameAnnotate: 'yoav.martin' },
    'Gil Orlev': { id: 'UFE2B37J9', nameAnnotate: 'gil.orlev' },
    'Roey Eldan': { id: 'UFEAWRW9L', nameAnnotate: 'roey.eldan' },
};

module.exports = slackUsers;